In [1]:
import pandas as pd


layer_7_train_csv_file_path = "D:\\ACA semester 7\\CS4622 - Machine Learning\\ML-Project\Data\\train.csv"
layer_7_valid_csv_file_path = "D:\\ACA semester 7\\CS4622 - Machine Learning\\ML-Project\Data\\valid.csv"
layer_7_test_csv_file_path = "D:\\ACA semester 7\\CS4622 - Machine Learning\\ML-Project\Data\\test.csv"

layer_12_train_csv_file_path = "D:\\ACA semester 7\\CS4622 - Machine Learning\\ML-Project\Data\\layer12\\train.csv"
layer_12_valid_csv_file_path = "D:\\ACA semester 7\\CS4622 - Machine Learning\\ML-Project\Data\\layer12\\valid.csv"
layer_12_test_csv_file_path = "D:\\ACA semester 7\\CS4622 - Machine Learning\\ML-Project\Data\\layer12\\test.csv"

In [2]:
def check_target_variables(file1, file2, target_column):
    df1 = pd.read_csv(file1)
    df2 = pd.read_csv(file2)
    
    # replce null values with the mean if the column = label_2
    if target_column == "label_2":
        df1[target_column].fillna(df1[target_column].mean(), inplace=True)
        df2[target_column].fillna(df2[target_column].mean(), inplace=True)
         
    are_target_variables_same = (df1[target_column] == df2[target_column]).all()

    if are_target_variables_same:
        return "SAME"
    else:
        return "NOT SAME"

In [3]:
print(check_target_variables(layer_7_train_csv_file_path, layer_12_train_csv_file_path, "label_1"))
print(check_target_variables(layer_7_valid_csv_file_path, layer_12_valid_csv_file_path, "label_1"))

SAME
SAME


In [4]:
print(check_target_variables(layer_7_train_csv_file_path, layer_12_train_csv_file_path, "label_2"))
print(check_target_variables(layer_7_valid_csv_file_path, layer_12_valid_csv_file_path, "label_2"))

SAME
SAME


In [5]:
print(check_target_variables(layer_7_train_csv_file_path, layer_12_train_csv_file_path, "label_3"))
print(check_target_variables(layer_7_valid_csv_file_path, layer_12_valid_csv_file_path, "label_3"))

SAME
SAME


In [6]:
print(check_target_variables(layer_7_train_csv_file_path, layer_12_train_csv_file_path, "label_4"))
print(check_target_variables(layer_7_valid_csv_file_path, layer_12_valid_csv_file_path, "label_4"))

SAME
SAME


In [7]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

c = np.vstack((a, b))

print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
import numpy as np

# Sample array
arr = np.array([10, 5, 200, 15, 30])

# Using np.argmax to find the index of the maximum value
index_of_max = np.argmax(arr)

# Output will be the index of the maximum value, which is 4 in this case
print(index_of_max)


2


In [23]:
from statistics import mode

# List of predictions from different models for one data point
predictions = [45, 45, 45, 45, 45, 3]

# Get the majority (mode) prediction
majority_prediction = mode(predictions)
print(majority_prediction)
print(predictions.count(majority_prediction))

45
5


In [19]:
# List of predictions from different models for one data point
predictions = [45, 45, 45, 45, 45, 3]

# List of confidence values (accuracies) for each model
confidences = [0.99, 0.93, 0.96, 0.97, 0.95, 0.25]

# Calculate the weighted mean prediction
weighted_mean = sum(prediction * confidence for prediction, confidence in zip(predictions, confidences)) / sum(confidences)

print(weighted_mean)


42.92079207920792


In [20]:
values = [0.99, 0.93, 0.96, 0.97, 0.95, 0.25]

# Calculate the sum of all values
total = sum(values)

# Divide each value by the total to normalize them
normalized_values = [value / total for value in values]

print(normalized_values)


[0.19603960396039605, 0.18415841584158418, 0.1900990099009901, 0.19207920792079208, 0.18811881188118812, 0.04950495049504951]


In [24]:
[0.1, 1, 10, 100]

[0.1, 1, 10, 100]